export const DEVELOPMENT_SERVER_URL = 'http://localhost:3000'
export const ENDPOINT_PATH = 'api'
export const ENDPOINT_VERSION = 'v1'
export const SEND_MESSAGE = 'send message'
export const RECEIVE_MESSAGE = 'receive message'
